### ISSUE TITLE
refatoracao_requisitos

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee#58]
**Descrição**

Refatoração do documento de requisitos.

**Objetivo**

Ajustar a documentação.

**Tarefas**

- [ ] Salvar versão atual do documento para controle de versão e rastreabilidade.
- [ ] Documentar corretamente requisitos não funcionais (Iago)
- [ ] Analisar e acrescentar mais requisitos não funcionais se for necessário (Iago e Maicon)
- [ ] Adicionar referências bibliográficas faltantes (Danilo)

**Informações adicionais**

**Checklist**
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [x] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by itallogravina** [comment]
Falta adicionar outras coisas
