### ISSUE TITLE
refatoracao_kanban

### ISSUE THREAD

**Issue by Gabrielle-Ribeiro** [UnBArqDsw2020-2/2020.2_G5_EasyCoffee#62]
**Descrição**

Refatorar quadro kanban.

**Objetivo**

Melhorar boards do quadro.

**Tarefas**

- [x] Alterar boards conforme necessário.
- [ ] Documentar as alterações feitas.  

**Informações adicionais**

**Checklist**
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [x] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by IagoTheophilo** [comment]
Não via a necessidade de documentar
